### ISSUE TITLE
Do you still consider duplicity a viable solution for qubes backups?

### ISSUE THREAD

**Issue by jpouellet** [Rudd-O/duplicity-qubes#1]
Considering your comment [here](https://github.com/QubesOS/qubes-issues/issues/858#issuecomment-233643226) (reproduced below) it would appear not.

> Update: Duplicity is no good for the process, because differential backups slow to a crawl.
> 
> We need to research other stuff, like Attic.

But this repo appears to have been created after that comment, so... maybe?

Not clear.

**Comment by Rudd-O** [comment]
Full backups work okay.  This code does the job.  Incrementals are slow, but that's what Duplicity does in any circumstance anyway, not limited to Qubes OS.
